name: Build
on:
  push: {}
  release: {}
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build
      run: make
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: ssh-agent-proxy
        path: ssh-agent-proxy
  release:
    name: Release
    runs-on: ubuntu-latest
    if: github.event_name == 'release'
    needs: build
    steps:
    - name: Download Artifact
      id: download
      uses: actions/download-artifact@v2
      with:
        name: ssh-agent-proxy
        path: ssh-agent-proxy
    - name: Generate Checksum
      run: sha256sum ${{ steps.download.outputs.download-path }} > sha256sum
    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ${{ steps.download.outputs.download-path }}
        asset_name: ssh-agent-proxy
        asset_content_type: application/octet-stream
    - name: Upload Checksum
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: sha256sum
        asset_name: sha256sum
        asset_content_type: text/plain
